### PR TITLE
Resolve #395 Taggings Not Retrieved From Controller

### LINKED ISSUE #395: Taggings Not Retrieved From Controller
**Describe the bug**
Upon load of `/find-out` page, all content types and all topic areas should appear.
Taggings controller error, json data not retreived.

```
jquery.min.js:2 GET https://staging.metrocommon.mapc.org/taggings.json?content_type=everything&topic_area=all%20topic%20areas 500
```

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Go to '/find-out
2. See error in browser dev tools

**Expected behavior**
User would expect to see all existing tagged items upon load of find-out page.
Page loads, but no items appear. 

If you select from either `content_type` or `topic_area` dropdowns, you do get expected results.
 
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] .   Mac OS
 - Browser [e.g. chrome, safari] .  Chrome
 - Version [e.g. 22] Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
New deployment of `develop` to `staging`.

### PR DESCRIPTION
**Pull request by smithWEBtek**
Remove seed migrations, add published_date validation & test
* Remove seed migrations which should not be in staging or production
* Remove csv files associated with seed migrations
* Remove images associated with seed migrations
* Add validation for published_date, to Announcement model
* Refactor test for published_date, to test for failed validation error message
 
Resolves #395

## Why is this change necessary?

- There were 3 migrations containing seed data which should not be pushed to staging or production.
- Due to the load order of these files, data prematurely loaded which did not match the final schema of the database. 
- This caused the taggings controller to fail at sorting data containing null values for sort_date, (specifically the Announcement published_date).

## How does it address the issue?
- Remove seed migrations for Announcement, Event and Report
- Remove code that seeds a single fake Event
- Remove the csv and png files associated with these ‘seed’ migrations

## What side effects does it have?
None. In a separate effort, these files and import code will be recreated in a rake task and a related folder for development locally.

### CODE REVIEW

**Comment by smithWEBtek** [comment]
Ok @mzagaja  this is ready for another look. Validations and tests added, and all tests passing.

File: spec/models/announcement_spec.rb [hunk 1]
```diff
@@ -1,10 +1,11 @@
 require "rails_helper"
 
 RSpec.describe Refinery::Announcements::Announcement, :type => :model do
+  let(:today) { Time.zone.now }
 
   it "it has a tag with a title of 'news' ", js: true do
     tag1 = Refinery::Tags::Tag.create(title: 'news', narrative: "We do announcements.", tag_type: "content_type")
-    announcement1 = FactoryBot.create(:announcement, title: 'Test Announcement Title')
+    announcement1 = FactoryBot.create(:announcement, title: 'Test Announcement Title', published_date: today)
```
Comment (mzagaja) [inline spec/models/announcement_spec.rb]: Did you consider adding published_date to `vendor/extensions/announcements/spec/support/factories/refinery/announcements.rb` factory and then setting `published_date` to nil on the test for no date?

Comment (smithWEBtek) [reply spec/models/announcement_spec.rb]: Thanks! done.
